const terminals = [
    {
        name: "Robinsons Dasma Terminal",
        position: { lat: 14.3014725, lng: 120.9540889 },
        image: "terminalpics/robdasma.png",
        description: "Near Uncle John - Jeeps available: DBB-C",
    },
    {
        name: "SM Dasmarinas Terminal",
        position: { lat: 14.3002471, lng: 120.9576322},
        image: "terminalpics/smdasma.png",
        description: "East Entrance - Jeeps available: Paliparan",
    },
    {
        name: "Paliparan (Near Mercury) Terminal",
        position: { lat: 14.3195395, lng: 120.9852583 },
        image: "terminalpics/mercurypaliparan.jpg",
        description: "Near Mercury Paliparan - Jeeps available: SM Molino ",
    },
    {
        name: "Paliparan (Kaagapay MTSC) Terminal",
        position: { lat: 14.32080121, lng: 120.9832877 },
        image: "terminalpics/multicab.png",
        description: "Jeeps available: Robinsons Dasma",
    },
    {
        name: "Paliparan (Sakayan ng Bayan) Terminal",
        position: { lat: 14.3201796, lng: 120.9791463 },
        image: "terminalpics/snb.jpg",
        description: "Jeeps available: Dasma Bayan, Paliparan",
    },
    {
        name: "Walter Terminal",
        position: { lat: 14.3253837, lng: 120.9407738},
        image: "",
        description: "Jeeps available: DBB-C, SM Molino, SM Pala Pala, DBB-1",
    },
    {
        name: "DBB-C (San Roque)",
        position: { lat: 14.3243836, lng: 120.9679677},
        image: "terminalpics/sanroque.jpg",
        description: "Barangay San Roque - Jeeps available: DBB-G, Dasma Bayan, Baclaran",
    },
    {
        name: "DBB-G",
        position: { lat: 14.3405631, lng: 120.9488987},
        image: "terminalpics/areag.jpg",
        description: "Jeeps available: DBB-F",
    },
    {
        name: "DBB-1",
        position: { lat: 14.3386277, lng: 120.9570035},
        image: "terminalpics/area1.jpg",
        description: "Jeeps available: DBB-F",
    },
    {
        name: "SM Molino",
        position: { lat: 14.3839152, lng: 120.9782028},
        image: "",
        description: "In front of SM Molino - Jeeps available: Paliparan",
    },
];

const toda = [
    { 
    name: "SM Hypermarket Mall Terminal",
      position: { lat: 14.3289, lng: 120.9603 }, //14.3289, 120.9603
      image: "terminalpics/katodamain.jpg",
      description: "KATODA - Area B",
    },
    { name: "SM Dasma TrikeTerminal",
      position: { lat: 14.3001, lng: 120.9577 },
      image: "terminalpics/lpstoda.png",
      description: "LPS TODA - Sampaloc I",
    },
    { name: "St. Charbel Main Terminal",
      position: { lat: 14.2995, lng: 120.9651 }, 
      image: "terminalpics/charm.png",
      description: "CHARM TODA - Sampaloc IV",
    },
    { name: "Sta Lucia Main Terminal",
      position: { lat: 14.3365036, lng: 120.9548081 }, 
      image: "terminalpics/slmt.jpg",
      description: "GATS TODA - Area 1",
    },
    { name: "Saint Jude Terminal",
      position: { lat: 14.3427913 , lng: 120.9625165 }, 
      image: "terminalpics/stjude.png",
      description: "GATS TODA - Salawag",
    },
    { name: "Main Terminal",
      position: { lat: 14.321141 , lng: 120.983922 }, 
      image: "terminalpics/mcpavsmain.jpg",
      description: "MC PAVS TODA - Paliparan",
    },
    { name: "Jollibee Paliparan Terminal",
      position: { lat: 14.3200635 , lng: 120.9850733 }, 
      image: "terminalpics/mcpavsjabee.jpg",
      description: "MC PAVS TODA - Paliparan",
    },
    { name: "Paliparan Site Terminal",
      position: { lat: 14.3200354, lng: 120.9805721 }, 
      image: "terminalpics/paliparansite.png",
      description: "MC PAVS TODA - Paliparan",
    },
    { name: "Unitop Dasmarinas Terminal",
      position: { lat: 14.2878091, lng: 120.9880551 }, 
      image: "terminalpics/unitop.png",
      description: "PATODA - Paliparan",
    },
    { name: "Mercury Paliparan Terminal",
      position: { lat: 14.3199826, lng: 120.9850935 }, 
      image: "terminalpics/mercury.jpg",
      description: "PATODA - Paliparan",
    },
    { name: "Main Terminal Salitran II Terminal",
      position: { lat: 14.3505024, lng: 120.9387929 }, 
      image: "terminalpics/mercury.jpg",
      description: "SAMICO TODA - Salitran",
    },
    { name: "SMCHC Main Gate Terminal",
      position: { lat: 14.32414383, lng: 120.9843569 }, 
      image: "terminalpics/smhcmain.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "Classic Terminal",
      position: { lat: 14.3339083, lng: 120.9765434 }, 
      image: "terminalpics/classic.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "North 1 Terminal",
      position: { lat: 14.3304932, lng: 120.9763219 }, 
      image: "terminalpics/north1.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "South 2 Washington Terminal",
      position: { lat: 14.32592012, lng: 120.9815496 }, 
      image: "terminalpics/south2.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "South 2 Washington Terminal",
      position: { lat: 14.32592012, lng: 120.9815496 }, 
      image: "terminalpics/south2.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "Phase 1 Terminal",
      position: { lat: 14.32418931, lng: 120.9781365 }, 
      image: "terminalpics/phase1terminal.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "Chesterey Terminal",
      position: { lat: 14.3272668, lng: 120.9775827 }, 
      image: "terminalpics/chesterey.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "Phase 3 Terminal",
      position: { lat: 14.3278912, lng: 120.9759101 }, 
      image: "terminalpics/phase3.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "Manukan Terminal",
      position: { lat: 14.32995115, lng: 120.9776295 }, 
      image: "terminalpics/manukan.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "Phase 5 Terminal",
      position: { lat: 14.32823596, lng: 120.9792419 }, 
      image: "terminalpics/phase5.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "Heights Terminal",
      position: { lat: 14.33307662, lng: 120.9771715 }, 
      image: "terminalpics/heights.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "Bangkok Terminal",
      position: { lat:14.32902599, lng: 120.9783953 }, 
      image: "terminalpics/bangkok.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "Lebanon (Central A) Terminal",
      position: { lat:14.32620692, lng: 120.9801602 }, 
      image: "terminalpics/lebanon.jpg",
      description: "SMCHC TODA - Salawag",
    },
    { name: "Salitran Terminal",
      position: { lat:14.350581, lng: 120.9390242 }, 
      image: "terminalpics/salitran.jpg",
      description: "SSDGC TODA - Salitran",
    },
     { name: "Salawag Main Terminal (Crossing)",
      position: { lat:14.3535527, lng: 120.9806048 }, 
      image: "terminalpics/salawagmain.jpeg",
      description: "SSDGC TODA - Salawag",
    },
    { name: "Brgy. Hall Salawag Terminal",
      position: { lat:14.344899, lng: 120.9817821 }, 
      image: "terminalpics/salawagbrgy.png",
      description: "SSDGC TODA - Salawag",
    },
    { name: "Savemore Salawag Terminal",
      position: { lat:14.3506601, lng: 120.9808103 }, 
      image: "terminalpics/ssavemore.png",
      description: "SSDGC TODA - Salawag",
    },
    { name: "The District Dasmarinas Terminal",
      position: { lat:14.358763, lng: 120.981854}, 
      image: "terminalpics/district.png",
      description: "SSDGC TODA - Salawag",
    },
    { name: "San Nicolas II Main Terminal",
      position: { lat:14.3178645, lng: 120.9705817}, 
      image: "terminalpics/vitoda.jpg",
      description: "VITODA - Area D",
    },
    { name: "Waltermart Dasmarinas Terminal",
      position: { lat:14.3252507, lng: 120.9406817}, 
      image: "terminalpics/waltermart.jpg",
      description: "TRODDAC - Zone IV",
    },

];




